### PR TITLE
Recursively find dependencies files

### PR DESCRIPTION
**Pull request by sl4mmy**
Recursively walk the dependencies dir specified on the command line looking for .dependencies files.

### CODE REVIEW

**Comment by sl4mmy** [comment]
Hey, dude-

@joewalnes and I are currently looking at ShavenMaven for use on a project at $WORK but it'd be really useful if it recursively looked for ```.dependencies``` files and mirrored their structure in the output dirs.  What do you think of the idea in general?

Also, commit a20a59e feels a little schizophrenic at the moment because of the combined use of the Java 8 Files/Path/Stream APIs with all your existing TotallyLazy usage, but I didn't see any recursive walk function in TotallyLazy's ```Files``` class so it seemed like mixing & matching was the simplest approach.  Let me know if you'd prefer to add that functionality to TotallyLazy instead, or replace more of the TotallyLazy use in ShavenMaven with Java 8 APIs, or whatever if you prefer something else instead.

**Comment by danielbodart** [comment]
It's called File.recursiveFiles in TL ;) or Files.recursiveFilesDirectoriesFirst.

Could you change it to use that instead?

Thanks

Dan

**Comment by sl4mmy** [comment]
Yep, definitely!  :)

**Comment by sl4mmy** [comment]
How's it look now?

**Pull request merged**
